spring:
  sql: # 처음에 DB 데이터 넣기 위한 설정(data.sql파일)
    init:
      mode: always

  datasource:
    url: jdbc:mysql://db-hobiday.c1248mguandn.ap-northeast-2.rds.amazonaws.com:3306/hobiday?serverTimezone=Asia/Seoul
#    url: jdbc:mysql://localhost:3306/hobiday?serverTimezone=Asia/Seoul
    username: admin
#    username: root
    password: 95206326
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true # 처음에 DB 데이터 넣기 위한 설정(data.sql파일)
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
        registration:
          kakao:
            client-id: f50d9911e72a37532cae75cba2277099 # 외부로 빼야함
            client-secret: FxIHbsanlyYyDot1yzsoaMS1y0T7fFgi # 외부로 빼야함
            client-authentication-method: client_secret_post
            redirect-uri: http://ec2-3-37-184-82.ap-northeast-2.compute.amazonaws.com:8080/login/oauth2/code/kakao
#            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-name: kakao
            scope: # 외부로 빼야함
              - profile_nickname
              - account_email
#              - profile_image

jwt:
  issuer: chyun5197@gmail.com
  secret_key: team8-project

